version: '3'

services:
  web:
    build: .
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=rindus
      - DB_USER=rindus
      - DB_PASSWORD=1234
      - DB_HOST=db-postgres
    depends_on:
      - db-postgres

  db-postgres:
    image: postgres
    environment:
      - POSTGRES_DB=rindus
      - POSTGRES_USER=rindus
      - POSTGRES_PASSWORD=1234
